// Generated by gencpp from file navigation/set_initial_pose.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_SET_INITIAL_POSE_H
#define NAVIGATION_MESSAGE_SET_INITIAL_POSE_H

#include <ros/service_traits.h>


#include <navigation/set_initial_poseRequest.h>
#include <navigation/set_initial_poseResponse.h>


namespace navigation
{

struct set_initial_pose
{

typedef set_initial_poseRequest Request;
typedef set_initial_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct set_initial_pose
} // namespace navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::navigation::set_initial_pose > {
  static const char* value()
  {
    return "b82a88bbcbaf998bb1f0cc2bc141c4bf";
  }

  static const char* value(const ::navigation::set_initial_pose&) { return value(); }
};

template<>
struct DataType< ::navigation::set_initial_pose > {
  static const char* value()
  {
    return "navigation/set_initial_pose";
  }

  static const char* value(const ::navigation::set_initial_pose&) { return value(); }
};


// service_traits::MD5Sum< ::navigation::set_initial_poseRequest> should match
// service_traits::MD5Sum< ::navigation::set_initial_pose >
template<>
struct MD5Sum< ::navigation::set_initial_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::set_initial_pose >::value();
  }
  static const char* value(const ::navigation::set_initial_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::set_initial_poseRequest> should match
// service_traits::DataType< ::navigation::set_initial_pose >
template<>
struct DataType< ::navigation::set_initial_poseRequest>
{
  static const char* value()
  {
    return DataType< ::navigation::set_initial_pose >::value();
  }
  static const char* value(const ::navigation::set_initial_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::navigation::set_initial_poseResponse> should match
// service_traits::MD5Sum< ::navigation::set_initial_pose >
template<>
struct MD5Sum< ::navigation::set_initial_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::navigation::set_initial_pose >::value();
  }
  static const char* value(const ::navigation::set_initial_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::navigation::set_initial_poseResponse> should match
// service_traits::DataType< ::navigation::set_initial_pose >
template<>
struct DataType< ::navigation::set_initial_poseResponse>
{
  static const char* value()
  {
    return DataType< ::navigation::set_initial_pose >::value();
  }
  static const char* value(const ::navigation::set_initial_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAVIGATION_MESSAGE_SET_INITIAL_POSE_H
