// Generated by gencpp from file navigation/set_initial_poseResponse.msg
// DO NOT EDIT!


#ifndef NAVIGATION_MESSAGE_SET_INITIAL_POSERESPONSE_H
#define NAVIGATION_MESSAGE_SET_INITIAL_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace navigation
{
template <class ContainerAllocator>
struct set_initial_poseResponse_
{
  typedef set_initial_poseResponse_<ContainerAllocator> Type;

  set_initial_poseResponse_()
    : done(false)  {
    }
  set_initial_poseResponse_(const ContainerAllocator& _alloc)
    : done(false)  {
  (void)_alloc;
    }



   typedef uint8_t _done_type;
  _done_type done;





  typedef boost::shared_ptr< ::navigation::set_initial_poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::navigation::set_initial_poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_initial_poseResponse_

typedef ::navigation::set_initial_poseResponse_<std::allocator<void> > set_initial_poseResponse;

typedef boost::shared_ptr< ::navigation::set_initial_poseResponse > set_initial_poseResponsePtr;
typedef boost::shared_ptr< ::navigation::set_initial_poseResponse const> set_initial_poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::navigation::set_initial_poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::navigation::set_initial_poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::navigation::set_initial_poseResponse_<ContainerAllocator1> & lhs, const ::navigation::set_initial_poseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.done == rhs.done;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::navigation::set_initial_poseResponse_<ContainerAllocator1> & lhs, const ::navigation::set_initial_poseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace navigation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::navigation::set_initial_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::navigation::set_initial_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::navigation::set_initial_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "89bb254424e4cffedbf494e7b0ddbfea";
  }

  static const char* value(const ::navigation::set_initial_poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x89bb254424e4cffeULL;
  static const uint64_t static_value2 = 0xdbf494e7b0ddbfeaULL;
};

template<class ContainerAllocator>
struct DataType< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "navigation/set_initial_poseResponse";
  }

  static const char* value(const ::navigation::set_initial_poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool done\n"
"\n"
;
  }

  static const char* value(const ::navigation::set_initial_poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_initial_poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::navigation::set_initial_poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::navigation::set_initial_poseResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAVIGATION_MESSAGE_SET_INITIAL_POSERESPONSE_H
